import Card from "@/components/card";
import IntroParagraph from "@/components/IntroParagraph";

export default function Page() {
  return (
    <>
      <IntroParagraph
        title="Welcome to the world of short stories!"
        description="This is a final project for the course ENGL 1170 (2024SP)."
      />

      <div className="w-full px-[100px] justify-center">
        {" "}
        <Card
          title="Stories"
          description="Selected stories that are included in ENGL 1170 (2024SP) course. These stories are all related to the class topic—Forever Changed: Loss, Resilience, and Transformations in Short Fiction"
          imageUrl="/homepage/stories.png"
          imageWidth={600}
          imageHeight={400}
          href="/stories"
        >
          {/* Additional content can be added here */}
        </Card>
      </div>
      <div className="w-full px-[100px] justify-center">
        {" "}
        <Card
          title="Statistics"
          description="View the statistics of the selected stories. The statistics are generated by the machine learning model that is fune-tuned on stories from the library. Statistics include horror, loss, resilience, nostalgia, and hope percentages."
          imageUrl="/homepage/statistics.png"
          imageWidth={600}
          imageHeight={400}
          href="/statistics"
        ></Card>
      </div>
    </>
  );
}
